import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "new page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex justify-center gap-2 list-none bg-purple-600 text-lg font-bold py-2   ">
          <li className="border-2 rounded-3xl px-2 py-1 border-white transition  -translate-y-1 duration-300">Home</li>
        <li className="border-2 rounded-3xl px-2 py-1 border-white">about</li>
        <li className="border-2 rounded-3xl px-2 py-1 border-white">Contact</li>
        <li className="border-2 rounded-3xl px-2 py-1 border-white">Faqs</li></div>
        
        
        <h2>my website</h2>
        {children}
        </body>
    </html>
  );
}
