//  parsein main 1 error ata ahi wo pata karn hai or solution b 








nepior/lepior ka sal hai ya nhi assighnement
||

non premitive main var ko call krne se value nhi aygi
balke location dega

anti gravity k bare main dekhna hai

assighnment 
promt main 10 family k name lena hai or array main save karna hai

example :
array familymembers = [""]

let user1 = prompt("enter your 1 family member")
user1.push(khan)

ye assignment hai
